config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root 'posts#index'

  resources :posts, only: [:show, :index]
  resources :tags, only: [:show]
  resources :categories, only: [:show]

  namespace :admin do
    resources :posts, except: [:show, :index]
    resources :categories, except: [:show]
    resources :pictures, only: [:create, :destroy]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :posts
  validates :name, presence: true

  has_ancestry
end

app/models/picture.rb
class Picture < ApplicationRecord
  mount_uploader :image, ImageUploader
end

app/models/post.rb
class Post < ApplicationRecord
  mount_uploader :image, ImageUploader
  
  has_many :taggings, dependent: :destroy
  has_many :tags, through: :taggings
  belongs_to :category

  validates :title, :summary, :body, presence: true

  def all_tags
    self.tags.map(&:name).join(', ')
  end

  def all_tags=(names)
    self.tags = names.split(',').map do |name|
      Tag.where(name: name.strip).first_or_create!
    end
  end
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :taggings
  has_many :posts, through: :taggings

  def self.counts
    self.select("name, count(taggings.tag_id) as count").joins(:taggings).group("name, taggings.tag_id")
  end
end

app/models/tagging.rb
class Tagging < ApplicationRecord
  belongs_to :post
  belongs_to :tag
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :confirmable, :validatable
end

app/controllers/admin/categories_controller.rb
class Admin::CategoriesController < ApplicationController
  before_action :authenticate_user!, except: [:show]
  before_action :set_category, only: [:edit, :update, :destroy, :show]

  def index
    @categories = Category.all
  end

  def new
    @category = Category.new
    @categories = Category.all.order(:name)
  end

  def create
    @category = Category.new(category_params)
    if @category.save
      redirect_to admin_categories_path, success: 'Категория успешно создана'
    else
      @categories = Category.all.order(:name)
      flash[:danger] = 'Категория не создана'
      render :new
    end
  end

  def edit
    @categories = Category.where("id != #{@category.id}").order(:name)
  end

  def update
    if @category.update_attributes(category_params)
      redirect_to admin_categories_path, success: 'Категория успешно обновлена'
    else
      @categories = Category.where("id != #{@category.id}").order(:name)
      flash[:danger] = 'Категория не обновлена'
      render :edit
    end
  end

  def destroy
    @category.destroy
    redirect_to admin_categories_path, success: 'Категория успешно удалена'
  end

  private

  def set_category
    @category = Category.find(params[:id])
  end

  def category_params
    params.require(:category).permit(:name, :parent_id)
  end
end

app/controllers/admin/posts_controller.rb
class Admin::PostsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  before_action :set_post, only: [ :edit, :update, :destroy ]

  def new
    @post = Post.new  
  end

  def create
    @post = Post.new(post_params)
    if @post.save
      redirect_to [:admin, @post], success: 'Статья успешно создана'
    else
      flash.now[:danger] = 'Статья не создана'
      render :new
    end
  end

  def edit
  end

  def update
    if @post.update_attributes(post_params)
      redirect_to [:admin, @post], success: 'Статья успешно обновлена'
    else
      flash.now[:danger] = 'Статья не обновлена'
      render :edit
    end
  end

  def destroy 
    @post.destroy
    redirect_to posts_path, success: 'Статья успешно удалена'
  end

  private

  def set_post
    @post = Post.find(params[:id])  
  end

  def post_params
    params.require(:post).permit(:title, :summary, :body, :image, :all_tags, :category_id)  
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery prepend: true
  add_flash_types :success, :danger, :info, :warning
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: :show

  def show
    @posts = Post.where(category_id: [@category.subtree_ids]).paginate(page: params[:page], per_page: 5)
  end

  private

  def set_category
    @category = Category.find(params[:id])
  end
end

app/controllers/pictures_controller.rb
class PicturesController < ApplicationController
  before_action :authenticate_user!
  def create
    @picture = Picture.new(image_params)
    @picture.save
    respond_to do |format|
      format.json { render :json => { url: @picture.image.url(:large), picture_id: @picture.id } }
    end
  end
  def destroy
    picture = Picture.find(params[:id])
    picture.destory
    respond_to do |format|
      format.json { render json: { status: :ok} }
    end  
  end

  private

  def image_params
    params.require(:picture).permit(:image)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: :show

  def index
    @posts = Post.paginate(page: params[:page], per_page: 2)  
  end

  def show
  end

  private

  def set_post
    @post = Post.find(params[:id])  
  end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  def show
    @tag = Tag.find_by(name: params[:id])
    @posts = @tag.posts
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def build_breadcrumb(category)
    result = []
    category.ancestors.each do |ancestor|
      result << content_tag(:li, class: "breadcrumb-item") do
        link_to(ancestor.name, ancestor)
      end
    end
    result << content_tag(:li, category.name, class: "breadcrumb-item active")
    result.join('').html_safe
  end

  def bootstrap_class_for(name)
    { success:"alert-success",
      error:  "alert-danger",
      danger: "alert-danger",
      alert:  "alert-warning",
      notice: "alert-info"
    }[name.to_sym] || name
  end
end

app/helpers/posts_helper.rb
module PostsHelper
  def tag_cloud(tags, classes)
    max = tags.sort_by(&:count).last
    tags.each do |tag|
      index = tag.count.to_f / max.count * (classes.size-1)
      yield(tag, classes[index.round])
    end
  end
end

app/views/admin/categories/_form.html.erb
<% if @category.errors.any? %>
<div class="alert alert-danger">
  <h5><%= t('common.errors') %></h5>
  <ul>
    <% @category.errors.full_messages.each do |message| %>
    <li><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>

<%= form_for [:admin, @category] do |f| %>
<div class="form-group">
  <%= f.label :name %>
  <%= f.text_field :name, class: 'form-control' %>
</div>

<div class="form-group">
  <%= f.label :parent_id %>
  <%= f.collection_select :parent_id, @categories, :id, :name, { include_blank: true }, class: 'form-control' %>
</div>

<div class="form-group">
  <%= f.submit t('.submit', action: @category.new_record? ? t('common.create'): t('common.edit')), class: 'btn btn-primary' %>
  <%= link_to t('common.back'), :back, class: 'btn btn-outline-secondary' %>
</div>
<% end %>

app/views/admin/categories/edit.html.erb
<h1><%= t('.title') %></h1>

<%= render 'form' %>

app/views/admin/categories/index.html.erb
<h1><%= t('.title') %></h1>

<div class="buttons_panel">
  <%= link_to 'Новая категория', new_admin_category_path, class: 'btn btn-outline-primary btn-sm' %>
</div>

<section id="categories">
  <table class="table">
    <thead>
      <tr>
        <th>#</th>
        <th>Название</th>
        <th>Категория родитель</th>
        <th></th>
      </tr>
    </thead>
    <tbody>
      <% @categories.each_with_index do |category, index| %>
      <tr>
        <td><%= index + 1 %></td>
        <td><%= category.name %></td>
        <td><%= category.parent.name if category.parent.present? %></td>
        <td>
          <%= link_to 'Изменить', edit_admin_category_path(category), class: 'btn btn-outline-primary btn-sm'  %>
          <%= link_to 'Удалить', admin_category_path(category), method: :delete, data: { confirm: 'Вы уверены?' }, class: 'btn btn-outline-danger btn-sm'  %>
        </td>
      </tr>
      <% end %>
    </tbody>
  </table>
</section>

app/views/admin/categories/new.html.erb
<h1><%= t('.title') %></h1>

<%= render 'form' %>

app/views/admin/posts/_form.html.erb
<% if @post.errors.any? %>
  <div class="alert alert-danger">
    <h5><%= t('common.errors') %> </h5>
    <ul>
      <% @post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<%= form_for [:admin, @post], html: { multipart: true } do |f| %>
  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :summary %>
    <%= f.text_area :summary, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :body %>
    <%= f.trix_editor :body, class: 'editor' %>
  </div>

  <div class="form-group">
    <%= f.label :category_id %>
    <%= f.collection_select :category_id, Category.order(:name), :id, :name, { include_blank: true }, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :all_tags %>
    <%= f.text_field :all_tags, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.file_field :image %>
  </div>

  <div class="form-group">
    <%= f.submit t('.submit', action: @post.new_record? ? 'Создать' : 'Изменить'), class: 'btn btn-primary' %>
    <%= link_to t('common.back'), :back, class: 'btn btn-outline-secondary' %>
  </div>
<% end %>

app/views/admin/posts/edit.html.erb
<h1><%= t('.title') %></h1>

<%= render 'form' %>

app/views/admin/posts/new.html.erb
<h1><%= t('.title') %></h1>

<%= render 'form' %>

app/views/categories/show.html.erb
<%= render 'shared/breadcrumb', category: @category %>

<h1><%= @category.name %></h1>

<section id="posts">
  <%= render @posts %>
</section>

<%= will_paginate @posts, renderer: 'BootstrapPaginationHelper::LinkRenderer' %>

app/views/categories/show.js.erb
$('#posts').append("<%= j render(partial: 'posts/delimeter') %>");
$('#posts').append("<%= j render(@posts) %>");

<% if @posts.next_page %>
    $('.pagination').replaceWith("<%= j  will_paginate(@posts, renderer: 'BootstrapPaginationHelper::LinkRenderer') %>");
<% else %>
    $('.pagination').remove();
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Myblog</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
      <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item active">
            <a class="nav-link" href="<%= posts_path %>">Все статьи <span class="sr-only">(current)</span></a>
          </li>
          <% Category.order(:name).roots.each do |category| %>
            <li class="nav-item <%= 'active' if current_page?(category_path(category)) %>">
              <%= link_to category.name, category, class: 'nav-link' %>
            </li>
          <% end %>
        </ul>
        <%#<%= link_to 'Новая статья', new_post_path, class: 'btn btn-outline-primary pull-xs-right' %1> %>
        <ul class="navbar-nav pull-xs-right">
          <% if user_signed_in? %>
            <li class="nav-item">
              <%= link_to "Выход", destroy_user_session_path, method: :delete, class: "nav-link" %>
            </li>
          <% else %>
            <li class="nav-item">
              <%= link_to "Вход", new_user_session_path, class: "nav-link" %>
            </li>
            <li class="nav-item">
              <%= link_to "Регистрация", new_user_registration_path, class: "nav-link" %>
            </li>
          <% end %>
        </ul>
      </nav>
    </div>
    <div class="container main">
      <div class="row">
        <div class="col-md-12">
          <% flash.each do |name, message| %>
            <div class="alert <%= bootstrap_class_for(name) %>">
              <button class="close" data-dismiss="alert">&times;</button>
              <%= message %>
            </div>
          <% end %>
        </div>
      </div>
      <div class="row">
        <div class="col-md-9">
          <%= yield %>
        </div>
        <div class="col-md-3">
          <%= render '/shared/submenu' %>
          <div class="tag_cloud">
            <% tag_cloud(Tag.counts, %w{tag1 tag2 tag3 tag4 tag5}) do |tag, css_class| %>
              <%= link_to tag.name, tag_path(tag.name), class: css_class %>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </body>
</html>

app/views/posts/_delimeter.html.erb
<div class="page_delimeter">Страница <%= params[:page] %></div>

app/views/posts/_disqus.html.erb
<div id="disqus_thread"></div>
<script>

  /**
  *  RECOMMENDED CONFIGURATION VARIABLES: EDIT AND UNCOMMENT THE SECTION BELOW TO INSERT DYNAMIC VALUES FROM YOUR PLATFORM OR CMS.
  *  LEARN WHY DEFINING THESE VARIABLES IS IMPORTANT: https://disqus.com/admin/universalcode/#configuration-variables*/
  /*
  var disqus_config = function () {
  this.page.url = PAGE_URL;  // Replace PAGE_URL with your page's canonical URL variable
  this.page.identifier = PAGE_IDENTIFIER; // Replace PAGE_IDENTIFIER with your page's unique identifier variable
  };
  */
  var disqus_config = function () {
    <%# <1%# this.page.url = '<%= request.base.url + request.original_fullpath %2>'; %>
    this.page.url = 'http://localhost.com<%= request.original_fullpath %>';
    this.page.identifier = '<%= @post.id %>';
  };
  (function () { // DON'T EDIT BELOW THIS LINE
    var d = document, s = d.createElement('script');
    s.src = 'https://myblog-5bxcyhvmkq.disqus.com/embed.js';
    s.setAttribute('data-timestamp', +new Date());
    (d.head || d.body).appendChild(s);
  })();
</script>
<noscript>Please enable JavaScript to view the <a href="https://disqus.com/?ref_noscript">comments powered by
    Disqus.</a></noscript>

app/views/posts/_post.html.erb
<article class="post">
  <section class="post-head">
    <h2><%= link_to post.title, post_path(post) %></h2>
    <small>
      <time><%= post.created_at.to_date.strftime("%d %B, %Y") %></time>
      <% if post.category.present? %>
        |
        <%= link_to post.category.name, post.category %>
      <% end %>
      <% if user_signed_in? %>
        |
        <%= link_to 'Изменить', edit_admin_post_path(post) %>
        |
        <%= link_to 'Удалить', admin_post_path(post), method: :delete, data: { confirm: 'Вы уверены?' } %>
      <% end %>
    </small>
  </section>
  <section class="post-summary clearfix">
    <%= image_tag post.image.url(:thumb), class: 'img-thumbnail thumb' if post.image? %>
    <p><%= post.summary %></p>
  </section>

  <section class="footer-summary">
    <%= raw post.tags.map(&:name).map{ |t| link_to t, tag_path(t), class: 'tag tag-primary' }.join(' ') %>
  </section>
</article>

app/views/posts/index.html.erb
<h1><%= t('.title') %></h1>

<% if user_signed_in? && current_user.admin? %>
  <%= link_to 'Новая статья', new_admin_post_path, class: 'btn btn-outline-primary btn-sm' %>
<% end %>

<section id='posts'>
  <%= render @posts %>
</section>

<%= will_paginate @posts, renderer: 'BootstrapPaginationHelper::LinkRenderer' %>

app/views/posts/index.js.erb
$('#posts').append("<%= j render(partial: 'delimeter') %>");
$('#posts').append("<%= j render(@posts) %>");

<% if @posts.next_page %>
    $('.pagination').replaceWith("<%= j  will_paginate(@posts, renderer: 'BootstrapPaginationHelper::LinkRenderer') %>");
<% else %>
    $('.pagination').remove();
<% end %>

app/views/posts/new.html.erb
<h1><%= t('.title') %></h1>

<%= render 'form' %>

app/views/posts/show.html.erb
<%= render 'shared/breadcrumb', category: @post.category %>

<article class="post">
  <section class="post-head">
    <h1><%= @post.title %></h1>
    <small>
      <time><%= @post.created_at.to_date.strftime("%d %B, %Y") %></time>
      <% if @post.category.present? %>
        |
        <%= link_to @post.category.name, @post.category %>
      <% end %>
      <% if user_signed_in? %>
        |
        <%= link_to 'Изменить', edit_admin_post_path(@post) %>
        |
        <%= link_to 'Удалить', admin_post_path(@post), method: :delete, data: { confirm: 'Вы уверены?' } %>
      <% end %>
    </small>
  </section>
  <section class="post-body">
    <%= image_tag @post.image.url(:large), class: 'img-show' if @post.image? %>
    <p><%= @post.body.html_safe %></p>
  </section>
</article>

<%= render 'disqus' %>

app/views/shared/_breadcrumb.html.erb
<% if category.present? && category.parent %>
  <ol class="breadcrumb">
    <%= build_breadcrumb(category) %>
  </ol>
<% end %>

app/views/shared/_submenu.html.erb
<div class="submenu">
  <h2>Категории</h2>
  <ul class="subnav nav-pills nav-stacked">
    <% Category.roots.each do |category| %>
    <li class="nav-item">
      <%= link_to category.name, category, class: "nav-link #{'active' if current_page?(category_path(category)) || @post.present? && @post.category == category}" %>
      <%= render 'shared/submenu_categories', categories: category.root.descendants.arrange %>
    </li>
    <% end %>
  </ul>
</div>

app/views/shared/_submenu_categories.html.erb
<ul class="subnav nav-pills nav-stacked nested_nav">
  <% categories.each do |category, children| %>
  <li>
    <%= link_to category.name, category, class: "nav-link #{'active' if current_page?(category_path(category)) || @post.present? && @post.category == category}" %>
    <%= render 'shared/submenu_categories', categories: children if children.present? %>
  </li>
  <% end %>
</ul>

app/views/tags/show.html.erb
<h1><%= @tag.name %></h1>

<% if @tag.posts.empty? %>
  <h2>Статей нет</h2>
<% else %>
  <%= render @tag.posts %>
<% end %>